# Dockerfile.build
FROM node:18-alpine AS builder
WORKDIR /app
COPY package.json ./
RUN yarn install --frozen-lockfile
COPY . .
COPY .env.local .env.local
RUN yarn build

RUN tar -czf build.tar.gz .next
